services:
  - type: web
    name: savranpay
    runtime: docker
    dockerfilePath: ./src/SavranPay.Api/Dockerfile
    dockerContext: .
    plan: starter
    healthCheckPath: /health/ready
    envVars:
      - key: ASPNETCORE_HTTP_PORTS
        value: 8080
      - key: DISABLE_HTTPS_REDIRECTION
        value: "true"
      - key: DataProtection__KeysPath
        value: /var/lib/savranpay/dataprotection-keys
      - key: Cors__AllowedOrigins__0
        value: https://savranpay.onrender.com
      - key: Cors__AllowedOrigins__1
        value: https://savranpay.netlify.app
      - key: Cors__AllowedOrigins__2
        value: https://savranpay-5yge.vercel.app
      - key: ConnectionStrings__Postgres
        fromDatabase:
          name: savranpay-postgres
          property: connectionString
      - key: Jwt__RequireAuthorization
        value: "true"
      - key: Jwt__SigningKey
        generateValue: true
    disk:
      name: savranpay-dataprotection
      mountPath: /var/lib/savranpay/dataprotection-keys
      sizeGB: 1

  - type: worker
    name: savranpay-worker
    runtime: docker
    dockerfilePath: ./src/SavranPay.Workers/Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: ConnectionStrings__Postgres
        fromDatabase:
          name: savranpay-postgres
          property: connectionString

databases:
  - name: savranpay-postgres
    plan: free
