<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BankTransfers.Application\BankTransfers.Application.csproj" />
    <ProjectReference Include="..\BankTransfers.Domain\BankTransfers.Domain.csproj" />
  </ItemGroup>
</Project>
